version 3

services:
  poll:
    container_name: poll
    build: poll
    ports:
      - 5000:80
    depends_on:
      - redis
    restart: always
    networks:
      - poll-tier
  worker:
    container_name: worker
    build: worker
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - back-tier
  result:
    container_name: result
    build: result
    ports:
      - 5001:80
    depends_on:
      - db
    restart: always
    networks:
      - result-tier
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
    networks:
      - poll-tier
      - back-tier
  db:
    container_name: db
    image: postgres
    restart: always
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=popeye

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
